version: '3.7'

services:
  postgresdb:
    container_name: qualisign_analysis_postgresdb
    build:
      context: postgresdb
    shm_size: '2gb'
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - qualisign_analysis_database_data:/var/lib/postgresql/data
    networks:
      - qualisign_analysis_network

  pgadmin:
    container_name: qualisign_analysis_pgadmin
    build:
      context: pgadmin
    ports:
      - ${PGADMIN_PORT}:80
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    depends_on:
      - postgresdb
    networks:
      - qualisign_analysis_network

volumes:
  qualisign_analysis_database_data:

networks:
  qualisign_analysis_network:
